name: Number-IP-RDP
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 1. Setup Admin Password
      run: |
        $pass = "Faiz@1611#Live"
        $admin = [adsi]"WinNT://localhost/Administrator,user"
        $admin.SetPassword($pass)
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: 2. Install Tailscale & Connect
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
        Start-Process tailscale.exe -ArgumentList "/quiet" -Wait
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }} --accept-routes --hostname FaizLivePC

    - name: 3. Show Number IP & Keep Alive
      run: |
        # Tailscale ka Number wala IP nikalna
        $ip = (& "C:\Program Files\Tailscale\tailscale.exe" ip -4)
        
        Write-Host "****************************************************" -ForegroundColor Green
        Write-Host "YOUR RDP IP (NUMBER): $ip" -ForegroundColor Yellow -BackgroundColor Red
        Write-Host "USERNAME: Administrator" -ForegroundColor Cyan
        Write-Host "PASSWORD: Faiz@1611#Live" -ForegroundColor Cyan
        Write-Host "****************************************************" -ForegroundColor Green
        
        $totalMinutes = 350
        $start = Get-Date
        while (((Get-Date) - $start).TotalMinutes -lt $totalMinutes) {
          Start-Sleep -Seconds 60
        }
        
