name: RDP-Number-IP-Setup
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 1. Setup User RDP & Password
      run: |
        # Username 'RDP' aur Password 'Faiz@1611#Live'
        $user = "RDP"
        $pass = "Faiz@1611#Live"
        
        net user $user $pass /add
        net localgroup administrators $user /add
        
        # RDP Settings On
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        powercfg /x -monitor-timeout-ac 0

    - name: 2. Install Tailscale & Connect
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
        Start-Process tailscale.exe -ArgumentList "/quiet" -Wait
        # Hostname 'FaizLivePC' fixed hai
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }} --accept-routes --hostname FaizLivePC

    - name: 3. Show Number IP & Keep Alive
      run: |
        # Wait for Tailscale to get IP
        Start-Sleep -Seconds 5
        $ip = (& "C:\Program Files\Tailscale\tailscale.exe" ip -4)
        
        Write-Host "****************************************************" -ForegroundColor Green
        Write-Host "YOUR RDP IP (NUMBER): $ip" -ForegroundColor Yellow -BackgroundColor Red
        Write-Host "USERNAME: RDP" -ForegroundColor Cyan
        Write-Host "PASSWORD: Faiz@1611#Live" -ForegroundColor Cyan
        Write-Host "****************************************************" -ForegroundColor Green
        
        # 6 Hour Loop (350 Minutes)
        $totalMinutes = 350
        $start = Get-Date
        while (((Get-Date) - $start).TotalMinutes -lt $totalMinutes) {
          Start-Sleep -Seconds 60
        }
        
